<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-QCSUJL0" name="com.OrangeHRM.TestCases.LoginTestCase" tests="14" failures="1" timestamp="8 Sep 2019 18:15:05 GMT" time="200.088" errors="0">
  <testcase name="logInNegative" time="20.859" classname="com.OrangeHRM.TestCases.LoginTestCase"/>
  <testcase name="clickOnYoutubeTest" time="8.590" classname="com.OrangeHRM.TestCases.LoginTestCase"/>
  <testcase name="logInNegative" time="12.615" classname="com.OrangeHRM.TestCases.LoginTestCase"/>
  <testcase name="verfylogoImage" time="8.077" classname="com.OrangeHRM.TestCases.LoginTestCase"/>
  <testcase name="clickOnTwiterTest" time="8.035" classname="com.OrangeHRM.TestCases.LoginTestCase"/>
  <testcase name="logInNegative" time="10.225" classname="com.OrangeHRM.TestCases.LoginTestCase"/>
  <testcase name="logInNegative" time="18.568" classname="com.OrangeHRM.TestCases.LoginTestCase"/>
  <testcase name="logInNegative" time="11.106" classname="com.OrangeHRM.TestCases.LoginTestCase"/>
  <testcase name="clickOnFacebookTest" time="10.125" classname="com.OrangeHRM.TestCases.LoginTestCase"/>
  <testcase name="testTitle" time="8.336" classname="com.OrangeHRM.TestCases.LoginTestCase">
    <failure type="java.lang.AssertionError" message="expected [OrangeHRM1] but found [OrangeHRM]">
      <![CDATA[java.lang.AssertionError: expected [OrangeHRM1] but found [OrangeHRM]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.OrangeHRM.TestCases.LoginTestCase.testTitle(LoginTestCase.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </failure>
  </testcase> <!-- testTitle -->
  <testcase name="logIn" time="13.162" classname="com.OrangeHRM.TestCases.LoginTestCase"/>
  <testcase name="totallinkTest" time="9.476" classname="com.OrangeHRM.TestCases.LoginTestCase"/>
  <testcase name="logIn" time="50.743" classname="com.OrangeHRM.TestCases.LoginTestCase"/>
  <testcase name="clickOnLinkedInTest" time="10.171" classname="com.OrangeHRM.TestCases.LoginTestCase"/>
</testsuite> <!-- com.OrangeHRM.TestCases.LoginTestCase -->
